# Generated by Django 6.0.5 on 2026-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Especialistas em Ar-Condicionado em Petrópolis', max_length=255)),
                ('subtitulo', models.TextField(default='Instalação, manutenção e higienização com garantia de qualidade.')),
                ('numero_whatsapp', models.CharField(default='5524992116050', help_text='Apenas números, com DDI e DDD.', max_length=20)),
                ('email_contato', models.EmailField(default='refrigeracaopetropolis@gmail.com', max_length=254)),
                ('link_instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone_emoji', models.CharField(default='❄️', help_text='Coloque um emoji para representar o serviço', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_exibicao', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem_exibicao'],
            },
        ),
    ]
